# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

substitutions:
    
    _SITE_DOMAIN: site-not-set.domain
    
    # Use a standard repo for testing
    _REPO_URL_HTTPS_TEST_CONTENT: https://github.com/mobybit/hugo-natrium-theme.git # default
    
    # The directory, relavent to either BUILD or IMAGE base folders
    # This structure is copied to the IMAGE later on and also used relative to the BUILD
    _PACKAGE_BASE_DIR_REPO_SITE: 'site/repo'
    _PACKAGE_BASE_DIR_REPO_THEME: 'theme/repo'
    _PACKAGE_BASE_DIR_REPO_CONTENT: 'content/repo'
    
    # Base build folders
    _BUILD_BASE_DIR_VOLUME: '/workspace'
    _BUILD_BASE_DIR_PACKAGE: '{$_BUILD_VOLUME_DIR}/package'
    
    # The full build path for each repo folder
    _BUILD_BASE_DIR_REPO_SITE: '${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_SITE}'
    _BUILD_BASE_DIR_REPO_THEME: '${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}'
    _BUILD_BASE_DIR_REPO_CONTENT: '${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_CONTENT}'
    
    # Within each repo folder, the location of configurable directories (for hugo commands) 
    # Short names that be overriden by trigger setup
    # THESE CAN BE SET SEPERATLY IN TRIGGER SETUP! (they are relative the remote git repo being used)
    _DIR_NAME_SITE: '.' #normally root of the repo base
    _DIR_NAME_THEME: '.' # the name of the folder containing the theme (. if same as the themes dir)
    _DIR_NAME_CONTENT: 'content' #normally /content of the repo base
    
    # Long names in order to make package base paths easier to understand
    _RELATIVE_INTERNAL_DIR_SITE: '${_DIR_NAME_SITE}'
    _RELATIVE_INTERNAL_DIR_THEME: '${_DIR_NAME_THEME}'
    _RELATIVE_INTERNAL_DIR_CONTENT: '${_DIR_NAME_CONTENT}'
        
    # Setup for the arguments, using both the base package location setup by this build file 
    # AND the relative paths used in the remote repos
    _PACKAGE_BASE_DIR_SITE: '${_PACKAGE_BASE_DIR_REPO_SITE}/${_RELATIVE_INTERNAL_DIR_SITE}'
    _PACKAGE_BASE_DIR_THEME: '${_PACKAGE_BASE_DIR_REPO_THEME}/${_RELATIVE_INTERNAL_DIR_THEME}'
    _PACKAGE_BASE_DIR_CONTENT: '${_PACKAGE_BASE_DIR_REPO_CONTENT}/${_RELATIVE_INTERNAL_DIR_CONTENT}'

    # Pathless, Hugo defaults
    _CONFIG_FILE_SITE: 'config.toml'
    _CONFIG_FILE_THEME: 'theme.toml'
    
    
steps:

# Setup workspace directories
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p $_BUILD_BASE_DIR_VOLUME
    mkdir -p $_BUILD_BASE_DIR_PACKAGE
    mkdir -p $_BUILD_BASE_DIR_REPO_SITE
    mkdir -p $_BUILD_BASE_DIR_REPO_THEME
    mkdir -p $_BUILD_BASE_DIR_REPO_CONTENT

# Clone the site repo to the workspace site folder
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '${_REPO_URL_HTTPS_SITE}'
  - '${_BUILD_BASE_DIR_REPO_SITE}'

# Clone the theme repo to the workspace site folder
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '${_REPO_URL_HTTPS_THEME}'
  - '${_BUILD_BASE_DIR_REPO_THEME}'

# Clone the test content repo 
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - '${_REPO_URL_HTTPS_TEST_CONTENT}'
  - '$_BUILD_BASE_DIR_REPO_CONTENT'

# Build the image

  # Dockefile copies site package to image, otherwise they wont be preloaded!
  # For flexibility the config items for folder locations can be set (as deterimined by this file) using docker build args

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/hugo-preloaded-implimentation-${_DOMAIN_SITE}'
  - '--file'
  - 'Dockerfile'
  #
  # Arguments used by image at BUILD TIME
  #
  - '--build-arg'
  # Used to copy all the downloaded repos to the image
  # /workspace/package
  - 'package_source=$_BUILD_BASE_DIR_PACKAGE'
  #
  # Arguments used by the hugo command line inside the image at RUN TIME
  #
  - '--build-arg'
  - 'site_config_file=$_CONFIG_FILE_SITE'
  #
  - '--build-arg'
  - 'theme_config_file=$_CONFIG_FILE_THEME'
  #
  - '--build-arg'
  - 'content_dir=$_PACKAGE_BASE_DIR_CONTENT'
  #
  - '--build-arg'
  - 'themes_dir=$_PACKAGE_BASE_DIR_THEME' # package/theme 
  #
  - '--build-arg'
  - 'theme_dir_name=$_DIR_NAME_THEME' # without full path /. or /some-theme-name = would make package/theme/some-theme-name
  #
  - '.'
    
# Push the image
images: ['gcr.io/${PROJECT_ID}/hugo-preloaded-implimentation-${_DOMAIN_SITE}']
