# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

#options:

#    substitution_option: 'ALLOW_LOOSE'

substitutions:
      
    # Base build folders
    _BUILD_BASE_DIR_PACKAGE: '/workspace/package'

    # The directory, relavent to either BUILD or IMAGE base folders
    # This structure is copied to the IMAGE later on and also used relative to the BUILD
    _PACKAGE_BASE_DIR_REPO_SITE: 'site/repo'
    _PACKAGE_BASE_DIR_REPO_THEME: 'theme/repo'
    _PACKAGE_BASE_DIR_REPO_CONTENT: 'content/repo'
      
    # For TESTING PURPOSES ONLY! (not the final build)
    _REPO_URL_HTTPS_CONTENT: 'https://github.com/mobybit/hugo-natrium-theme.git'
    
    _PACKAGE_BASE_DIR: '/package'
    
    # Pathless, Hugo defaults
    _CONFIG_FILE_SITE: 'config.toml'
    _CONFIG_FILE_THEME: 'theme.toml'    
    
    
steps:

# Setup workspace directories
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}
    \
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_SITE}
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_CONTENT}
    \
    echo 'Listing child directories in workspace:'
    ls -d ${_BUILD_BASE_DIR_PACKAGE}
    echo 'Finding directories in package:'
    find ${_BUILD_BASE_DIR_PACKAGE} -type d

# Clone the site repo to the workspace site folder
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - ${_REPO_URL_HTTPS_SITE}
  - ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_SITE}

# Clone the theme repo to the workspace site folder
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - ${_REPO_URL_HTTPS_THEME}
  - ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}

# Clone the test content repo 
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - ${_REPO_URL_HTTPS_CONTENT}
  - ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_CONTENT}

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'POST GIT CLONE: Finding directories in workspace:'
    find . -type d ! -path "*/\.*"
    echo 'Listing directories in workspace:'
    ls -d

# Build the image

  # Dockefile copies site package to image, otherwise they wont be preloaded!
  # For flexibility the config items for folder locations can be set (as deterimined by this file) using docker build args

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/hugo-preloaded-implimentation-${_DOMAIN_SITE}'
  #
  - '--file'
  - 'Dockerfile'
  #
  # Arguments used by image at BUILD TIME
  #
  - '--build-arg'
  - 'package_source=${_BUILD_BASE_DIR_PACKAGE}'
  #
  #
  # Arguments used by the hugo command line inside the image at RUN TIME
  #
  - '--build-arg'
  - 'builder_package_dir=${_CONFIG_FILE_SITE}'
  #
  - '--build-arg'
  - 'theme_config_file=${_CONFIG_FILE_THEME}'
  #
  - '--build-arg'
  - 'content_dir=${_PACKAGE_BASE_DIR}/${_PACKAGE_BASE_DIR_REPO_CONTENT}'
  #
  - '.'
