# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

#options:

#    substitution_option: 'ALLOW_LOOSE'

substitutions:
      
    # Base build folders
    _BUILD_BASE_DIR_VOLUME: '/workspace'
    _BUILD_BASE_DIR_PACKAGE: '${_BUILD_BASE_DIR_VOLUME}/package'

    # The directory, relavent to either BUILD or IMAGE base folders
    # This structure is copied to the IMAGE later on and also used relative to the BUILD
    _PACKAGE_BASE_DIR_REPO_SITE: 'site/repo'
    _PACKAGE_BASE_DIR_REPO_THEME: 'theme/repo'
    _PACKAGE_BASE_DIR_REPO_CONTENT: 'content/repo'
      
    # For TESTING PURPOSES ONLY! (not the final build)
    _REPO_URL_HTTPS_CONTENT: 'https://github.com/mobybit/hugo-natrium-theme.git'
    
    
steps:

# Setup workspace directories
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p ${_BUILD_BASE_DIR_VOLUME}
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}
    \
    \
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_SITE}
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}
    mkdir -p ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_CONTENT}
    \
    echo 'Created directories:'
    find ${_BUILD_BASE_DIR_PACKAGE} -type d

# Clone the site repo to the workspace site folder
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - ${_REPO_URL_HTTPS_SITE}
  - ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_SITE}

# Clone the theme repo to the workspace site folder
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - ${_REPO_URL_HTTPS_THEME}
  - ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_THEME}

# Clone the test content repo 
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - ${_REPO_URL_HTTPS_CONTENT}
  - ${_BUILD_BASE_DIR_PACKAGE}/${_PACKAGE_BASE_DIR_REPO_CONTENT}

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo 'POST GIT CLONE: Listing all workspace directories:'
    find . -type d ! -path "*/\.*"
