# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

options:

    substitution_option: 'ALLOW_LOOSE'

substitutions:
    
    _SITE_DOMAIN: site-not-set.domain
    
    # Use a standard repo for testing
    _REPO_URL_HTTPS_TEST_CONTENT: https://github.com/mobybit/hugo-natrium-theme.git # default
    
    # The directory, relavent to either BUILD or IMAGE base folders
    # This structure is copied to the IMAGE later on and also used relative to the BUILD
    _PACKAGE_BASE_DIR_REPO_SITE: 'site/repo'
    _PACKAGE_BASE_DIR_REPO_THEME: 'theme/repo'
    _PACKAGE_BASE_DIR_REPO_CONTENT: 'content/repo'
